### ISSUE TITLE
Zygote.OneElement does not properly reshape

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Zygote.jl#1080]
MWE:

```julia
Z = randn(rng, Float32, (n,m))
Z .= Flux.Zygote.OneElement(0.1, (2,), axes(Z))
vec(Z) .= vec(Flux.Zygote.OneElement(0.1, (2,), axes(Z)))
```

**Comment by DhairyaLGandhi** [comment]
I don't think one element is something end users need to interact with. Where are we seeing this get leaked to user code?

**Comment by ChrisRackauckas** [comment]
In the DiffEq adjoints it's passed back: https://github.com/SciML/DiffEqSensitivity.jl/blob/v6.58.0/src/concrete_solve.jl#L207

**Comment by ChrisRackauckas** [comment]
```julia
function Base.reshape(x::Flux.Zygote.OneElement,shp::Int)
    prev_shp = Base.to_shape(x.axes)
    @assert prod(prev_shp) == prod(shp)
    linear_ind = LinearIndices(prev_shp)[CartesianIndex(x.ind)]
    Flux.Zygote.OneElement(x.val,(linear_ind,),(Base.OneTo(shp),))
end

function Base.reshape(x::Flux.Zygote.OneElement,shp::Tuple{Int64, Vararg{Int64, N}}) where N
    @assert prod(Base.to_shape(x.axes)) == prod(shp)
    Flux.Zygote.OneElement(x.val,x.ind,((Base.OneTo(s) for s in shp)...,))
end
```

Seems to be what's necessary.

**Comment by DhairyaLGandhi** [comment]
It's of course difficult to deal with in the presence of complex adjoint code. We likely need regular arrays to handle arbitrary operations happening on them in intermediate computations happening in custom adjoints. It's also not going to work neatly with GPUs in its current state.

**Comment by ChrisRackauckas** [comment]
With those reshapes this seems fine:

```julia
using Zygote, CUDA
Z = randn(rng, Float32, (n,m)) |> gpu
Z .= Flux.Zygote.OneElement(0.1, (2,1), axes(Z))
vec(Z) .= vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z)))
```

**Comment by ChrisRackauckas** [comment]
However,

```julia
vec(Z) .= -vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z)))
```

hits a GPU kernel generation error.

**Comment by DhairyaLGandhi** [comment]
The reshape code looks about right. Wouldn't we need to calculate the resultant indices in the second `Tuple{Int...}` case?

**Comment by ChrisRackauckas** [comment]
oh yes you would.

**Comment by ChrisRackauckas** [comment]
```julia
function Base.reshape(x::Flux.Zygote.OneElement,shp::Tuple{Int64, Vararg{Int64, N}}) where N
    prev_shp = Base.to_shape(x.axes)
    @assert prod(Base.to_shape(x.axes)) == prod(shp)
    cartesian_ind = LinearIndices(prev_shp)[CartesianIndex(x.ind)]
    Flux.Zygote.OneElement(x.val,cartesian_ind,((Base.OneTo(s) for s in shp)...,))
end
```

would probably work.

**Comment by ChrisRackauckas** [comment]
@maleadt here's an MWE:

```julia
using Zygote, CUDA
function Base.reshape(x::Zygote.OneElement,shp::Int)
    prev_shp = Base.to_shape(x.axes)
    @assert prod(prev_shp) == prod(shp)
    linear_ind = LinearIndices(prev_shp)[CartesianIndex(x.ind)]
    Flux.Zygote.OneElement(x.val,(linear_ind,),(Base.OneTo(shp),))
end

function Base.reshape(x::Zygote.OneElement,shp::Tuple{Int64, Vararg{Int64, N}}) where N
    @assert prod(Base.to_shape(x.axes)) == prod(shp)
    Flux.Zygote.OneElement(x.val,x.ind,((Base.OneTo(s) for s in shp)...,))
end

Z = randn(rng, Float32, (n,m)) |> gpu
Z .= Flux.Zygote.OneElement(0.1, (2,1), axes(Z))
vec(Z) .= vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z))) # works!

vec(Z) .= -vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z))) # doesn't work!
```

I'm curious why adding that `-` makes it so it cannot compile on GPUs anymore.

**Comment by mcabbott** [comment]
The OneElement constructor isn't very defensive, because it was assumed this only had one caller. What's written here should probably be an error, since it constructs something whose `ndims` doesn't match its `axes`, and it is no surprise that this confuses many Base functions downstream:
```
julia> using Zygote

julia> Z = rand(2,3);

julia> ze = Zygote.OneElement(0.1, (2,), axes(Z))  # this is a broken object, should be illegal!
2×3 Zygote.OneElement{Float64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 0.0
 0.1

julia> ndims(ze)
1

julia> size(ze)  # doesn't match ndims & type
(2, 3)

julia> @which vec(ze)  # does nothing at all
vec(a::AbstractVector) in Base at abstractarraymath.jl:42

julia> vec(ze) === ze
true
```
Does Zygote construct such things? If it does that's a bug which ought to be fixed, and a MWE of that would be appreciated. It's possible that the rule put too little thought into linear indexing, although a naiive attempt to fool it does not work:
```
julia> gradient(x -> x[1], rand(2,3))[1]
2×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.0  0.0

julia> gradient(x -> x[1,1], rand(2,3))[1]
2×3 Zygote.OneElement{Float64, 2, Tuple{Int64, Int64}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 1.0  0.0  0.0
 0.0  0.0  0.0
```

**Comment by DhairyaLGandhi** [comment]
Well, Yes, the rule does not cover the case of different indexing techniques or consider the array type (StarWarsArray.jl, OffsetArrays.jl esque)

**Comment by ChrisRackauckas** [comment]
Sometimes you just need to `vec` values in a pullback. I don't think it makes sense to blanket say that `vec` is never an operation that should ever be used in any pullback function ever. The problem is that the delta pullback value is sometimes a Zygote.OneElement, so algorithms that would want to `vec` will fail.

**Comment by mcabbott** [comment]
Yes I agree `vec` should always be safe, and understand why you want it. I don't see anyone saying you must avoid this. 

What you must avoid is constructing objects whose type doesn't match their properties. The OneElement constructor presently lacks a guardrail to make this construction an error, which is why you can make one by hand. But if you can make Zygote make one for you, that would be much more concerning.

**Comment by ChrisRackauckas** [comment]
Oh, I didn't see that I made an illegal Zygote.OneElement. It's the same error I get in a pullback though, which is disconcerting. MWE that got that is the first thing in https://github.com/SciML/DiffEqFlux.jl/issues/632

**Comment by mcabbott** [comment]
Is that on Flux master? You say " if we try to say |> gpu inside of the rhs function" which means you may need things fixed in   https://github.com/FluxML/Flux.jl/pull/1704 (almost a month ago). Without that you may still hit problems like #1005. 

But I don't know that that's the problem. Independent of that, if you have managed to get Zygote to make an illegal OneElement, that's very concerning, and would be worth trying to figure out. Maybe adding the guardrail above (to make construction a MethodError) might at least produce stack traces closer to the constructor. 

Is that stack trace for SciML/DiffEqFlux.jl#632 posted somewhere?

**Comment by maleadt** [comment]
> I'm curious why adding that `-` makes it so it cannot compile on GPUs anymore.

```
julia> typeof(vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z))))
Zygote.OneElement{Float64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}

julia> typeof(-vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z))))
Vector{Float64} (alias for Array{Float64, 1})
```

It works if you broadcast the `-`:

```
vec(Z) .= .-vec(Flux.Zygote.OneElement(0.1, (2,1), axes(Z)))
```

**Comment by ChrisRackauckas** [comment]
That `.-` seems to be the key. Thanks.

**Comment by mcabbott** [comment]
`z .= -x` will always add a copy which `z .= .-x` avoids, but is easy to miss. It might be friendly to provided methods for OneElement which avoid this, since it's so easy. I can't think of any downsides.

**Comment by ChrisRackauckas** [comment]
Yeah, that's the downstream fix to that specific problem. I think that means everything here is answered.
