### ISSUE TITLE
Problems with using gradient iteratively 

### ISSUE THREAD

**Issue by benedict-96** [FluxML/Zygote.jl#1099]
When I'm using `gradient` iteratively and performing computations in-between the two gradient operations, I'm mostly getting garbage. I can't index (square brackets; first example), matrix multiplication with an externally defined matrix (second example)  or even trivial operations like `^.1` (last example; this does not give an error, but rather returns zero). The internally defined matrix and the ``projection operators'' (third and forth example) are a workaround for the indexing problem. 

 ```julia
using Zygote


##############################################################
#####doesn't work
function loss(x,b)
        predict(x,b) = (x .+ b)[2]^2
        return gradient(χ -> predict(χ,b),x)[1][2]^2
end

update_b(x,b) = gradient(β -> loss(x,β),b)
update_b(rand(2),rand(2))

############################################################
###### doesn't work
P = [0 0; 0 1]

predict(x,b) = sum(P*(x .+ b).^2)
loss(x,b) = sum(P*(gradient(χ -> predict(χ,b),x)[1]))^2

update_b(x,b) = gradient(β -> loss(x,β),b)
update_b(rand(2),rand(2))

#####does work
function loss(x,b)
        P = [0 0; 0 1]
        predict(x,b) = sum(P*(x .+ b).^2)
        return sum(P*(gradient(χ -> predict(χ,b),x)[1]))^2
end

update_b(x,b) = gradient(β -> loss(x,β),b)
update_b(rand(2),rand(2))

##############################################################
#projection operator -> does work
proj2(x) = sum([0 0 ; 0 1]*x)
proj1(x) = sum([1 0 ; 0 0]*x)

predict(x,b) = proj2(x .+ b)^2
loss(x,b) = proj2(gradient(χ -> predict(χ,b),x)[1])^2

update_b(x,b) = gradient(β -> loss(x,β),b)
update_b(rand(2),rand(2))


################################################################
#When I'm performing a simple ^.1 operation, the output becomes zero!

function predict_t(x,a,b)
        x = vcat(proj1(x),proj2(x).*exp.(a*proj1(x) + b))
        return x
end

H₁(x) = .5*sum(x.^2)
##this works
loss_test(x,a,b) = proj2(gradient(χ -> H₁(predict_t(χ,a,b)),x)[1])
gradient(α -> loss_test([1,.2],α,0),0)
#this gives 0
loss_test2(x,a,b) = proj2(gradient(χ -> H₁(predict_t(χ,a,b)),x)[1])^1.
gradient(α -> loss_test2([1,.2],α,0),0)
```

**Comment by ToucheSir** [comment]
The code above isn't performing computations between two parallel gradient operations, but rather calculating the product of first and second order derivatives (nesting N calls to `gradient` gets you Nth order derivatives). If you could describe what the desired results are in math/pseudocode terms we might be able to help you, but otherwise it's almost impossible to guess the exact intent of the code above.

**Comment by ToucheSir** [comment]
So in pseudo-Julia, what you want is something like this?

```julia
gradient(θ) do
   ∂δ, = gradient(δ) do δ
       abs.(H₁(r, δ))
   end
   sum(f(r, δ) .* ∂δ) 
end
```

Where `f` and `H₁` are vectorized functions (i.e. NNs) implicitly parameterized in terms of `θ`.

**Comment by benedict-96** [comment]
Yes! That's almost it. Just that `f` and `H₁` are scalars. And `δ` would also be 1d.

**Comment by ToucheSir** [comment]
right, I vectorized them assuming that they would be Flux-like NNs (batched input, batched output), but obviously you know your code best :) Without knowing the internals of `f` and `H₁` it's difficult to say whether nesting Zygote's reverse mode would work, but it doesn't hurt to give things a try. Otherwise, ForwardDiff is probably the best choice for mostly scalar AD. This stuff is mostly over my head though, so I'll let the more qualified contributors here chime in.
