### ISSUE TITLE
Broadcast gradient error

### ISSUE THREAD

**Issue by cossio** [FluxML/Zygote.jl#1132]
![image](https://user-images.githubusercontent.com/10637482/145546368-949a94d2-037d-4c31-9e01-b39c600328b5.png)

**Comment by cossio** [comment]
Could be related to https://github.com/FluxML/Zygote.jl/pull/1001, which I think adds the ForwardDiff code path for broadcasted operations.

**Comment by cossio** [comment]
I tried adding a rule like this:

```julia
import DiffRules, IrrationalConstants, SpecialFunctions

∂logerfcx(x) = 2 * (x - inv(SpecialFunctions.erfcx(x)) / IrrationalConstants.sqrtπ)
DiffRules.@define_diffrule SpecialFunctions.logerfcx(x) = :(∂logerfcx($x))
```

But I get the exact same error afterwards.

**Comment by DhairyaLGandhi** [comment]
Worth noting that broadcasting isn't picking up adjoints defined by hand due to recent changes to special case numeric arrays. I think that should be considered a bug.

```julia
julia> function fn(x)
         x ^ 2
       end
fn (generic function with 1 method)

julia> gradient(x -> sum(fn.(x)), ones(3,3))
([2.0 2.0 2.0; 2.0 2.0 2.0; 2.0 2.0 2.0],)

julia> gradient(x -> sum(fn.(x)), 3.)
(6.0,)

julia> gradient(x -> sum(fn(x)), 3.)
(6.0,)

julia> Zygote.@adjoint function fn(x)
         fn(x), Δ -> (1.,)
       end

julia> gradient(x -> sum(fn.(x)), ones(3,3))
([2.0 2.0 2.0; 2.0 2.0 2.0; 2.0 2.0 2.0],)

julia> gradient(x -> sum(fn(x)), 3.)
(1.0,)
```

**Comment by ToucheSir** [comment]
Assuming it works, Zygote's built-in forward mode would still require an `@tangent` definition instead of an `@adjoint`. So in that sense you have to pick your poison: `@tangent`, `@define_diffrule` or maybe even `frule`.

**Comment by cossio** [comment]
> Assuming it works, Zygote's built-in forward mode would still require an `@tangent` definition instead of an `@adjoint`. So in that sense you have to pick your poison: `@tangent`, `@define_diffrule` or maybe even `frule`.

Oh, can you point to an example where `@tangent` is explained?
I can't find anything in the docs https://fluxml.ai/Zygote.jl/stable/search/?q=tangent.

**Comment by mcabbott** [comment]
I think forward vs reverse is a distraction here, as for simple R^2 -> R functions they will hardly differ. The problem is that Zygote tends to break type inference, and doing that in a tight loop (like broadcasting) murders performance. 

I have no idea whether Zygote's abandoned forward mode would do any better; it relies on the same IRTools tricks but perhaps inference is easier. @cossio this was never documented, never really got beyond proof of principle. 

The present code calls `Broadcast.combine_eltypes` which calls type inference for the primal. A safer way to guard the ForwardDiff fast path would be to similarly check that the dual function infers to return a `Dual` number. It will infer to `Union{}` if there are missing methods, as in this case, and then you could take the all-Zygote fallback path.

**Comment by ToucheSir** [comment]
> https://github.com/FluxML/Zygote.jl/blob/master/src/forward/lib.jl

It isn't explained anywhere that I know of. You could try to piece together the internals from #503, but based on the comments there I imagine you've read through it already. As Michael mentioned, development kind of fell off a cliff after the first PR and for whatever reason there hasn't been enough appetite to pick it back up.
