### ISSUE TITLE
[Suggestion] withhessian

### ISSUE THREAD

**Issue by raphaelchinchilla** [FluxML/Zygote.jl#1139]
This is a suggestion to implement a function `withhessian`, similar to `withgradient` and `withjacobian` that would return the value of the function, its gradient and its hessian.

**Comment by ToucheSir** [comment]
Relatedly, do we want to have a discussion about adding support for AbstractDifferentiation (or vice versa)? https://github.com/JuliaDiff/AbstractDifferentiation.jl#value-and-derivativegradientjacobianhessian is basically `withhessian` but standardized.

**Comment by mcabbott** [comment]
Since `withgradient` gives a NamedTuple, probably `withhessian` should return the gradient too (`val, grad, hess`) since it will surely have it along the way, and you can ignore it if not needed. This is like `AD.value_gradient_and_hessian` (and fully supporting AbstractDifferentiation would be neat, if a slightly bigger project.)

If you look at the implementation,  https://github.com/FluxML/Zygote.jl/blob/master/src/lib/grad.jl#L76 , keeping the gradient is almost trivial, since it just means using `withjacobian` for the outer step, or for the dual number version, just dropping the `[2]`:
```
julia> f = x -> sum(x.^3);

julia> Zygote.forward_jacobian(x -> Zygote.gradient(f, x)[1], [1 2; 3 4])
([3 12; 27 48], [6 0 0 0; 0 18 0 0; 0 0 12 0; 0 0 0 24])

julia> Zygote.gradient(f, [1 2; 3 4])
([3.0 12.0; 27.0 48.0],)
```
Keeping the value looks to be tricker, will involve messing with `forward_jacobian`. Or deciding that one forward evaluation is so cheap compared to the hessian as not to matter?

**Comment by raphaelchinchilla** [comment]
> keeping the gradient is almost trivial, since it just means using withjacobian

I agree, this is what I am doing now.

> Or deciding that one forward evaluation is so cheap compared to the hessian as not to matter?

This is also what I am doing now, but maybe that would not be true, for instance if Zygote, the Julia compiler and LLVM can drastically simplify the expression of the hessian (something similar to [what is shown in this video](https://youtu.be/R81pmvTP_Ik?t=1220) ).
 
In any case, it would be a nice to have if it is simple to implement, or if its implementation could benefit some more general goal, such as moving towards supporting AbstractDifferentiation . If not, I think this issue could be closed

**Comment by mcabbott** [comment]
I'd be OK with adding the very simple one, which evaluates `f(x)`, and then the other two together. If you can think up a clever way to get all three at once, that would be even better of course.

While sometimes a derivative might compile down to be even faster than the simple evaluation, my guess is that Hessians (with array `x`) are always going to be pretty expensive, maybe at least `length(x)` times the forward pass? Haven't thought very hard, maybe there are exceptions. Certainly `length(x)^2` storage...

**Comment by raphaelchinchilla** [comment]
> If you can think up a clever way to get all three at once, that would be even better of course.

Before opening this issue, I thought about how one would be able to do it, but could not figure it out. I am not an expert in Julia, so there could be something in the internal mechanics of Zygote that I oversaw. 

I am closing this issue as it does not seem that there is an especially good way to implement it besides what you have mentioned.
