### ISSUE TITLE
Mutation buffers

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Zygote.jl#122]
As an alternative (or stopgap) for #75, I'm considering introducing an explicitly mutable array-like (but not AbstractArray) type. Usage would look something like

```julia
buf = buffer(x, length(x), 5) # like `similar`
for i = 1:5
  buf[:, i] = x
end
return copy(buf) # return a normal array
```

(`copy` need not involve an actual copy if it disables further mutation.) The idea is that only non-capturing operations would be allowed on buffers (basically indexing) where it's convenient, and then you go back to an array for your mathematical operations.

For normal ML usage, I think this is a clear win over #75; it's really easy to implement, not noticeably less convenient, and the extra constraints give us some nice memory usage optimisations.

However, for differentiable programming it's a bit trickier; it's not ideal to have to ask existing packages to make concessions. Not having #75 is going to mean some programs are not going to be differentiable when they could be, unless they rewrite to use buffers or support immutable arrays (arguably good practice). On the flip side, much the same things could be said about `eval` and exception-based control flow.

**Comment by jpsamaroo** [comment]
For cases where existing packages would not be willing to make changes to support this buffer type, it might be helpful to show how easily one could implement the necessary changes with some Cassette overdubs or a custom pass, if possible. The difficulty of that exercise should indicate whether this change is a suitable approach, or if #75 is necessary instead.

**Comment by antoine-levitt** [comment]
I don't know much about the implementation of reverse AD so feel free to disregard, but for non-ML applications in scientific computing, mutation certainly is pretty useful. Computing in place is a standard and recommended technique to get optimal performance in julia (eg https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Pre-allocating-outputs-1). By contrast, `eval` and exception-based control flow are usually discouraged in optimized code.

The attraction of AD for me (rather than implementing derivatives by hand) is to be able to have a single code base for the optimized implementation of a functionality and for computing its derivative (even if the derivative is less performant than what I would have done by hand). Having to use custom types to help AD along complicates that.

**Comment by MikeInnes** [comment]
Yes, definitely agreed about the downsides of this. The flip side is that arguably a good Julia code base should be written generically enough to handle things like immutable arrays anyway; but the unfortunate reality is that Julia doesn't have good enough abstractions to do that right now, which means we have to deal with in-place code at some point.

> it might be helpful to show how easily one could implement the necessary changes with some Cassette overdubs or a custom pass, if possible.

It's not that easy to automate this with a compiler pass, otherwise we'd just to it by default in Zygote. One possible option is to allow mutation only within specific context, but adds as much complexity internally as #75 would.
