### ISSUE TITLE
Gradients for nested struct fields are super slow

### ISSUE THREAD

**Issue by bogiebro** [FluxML/Zygote.jl#1256]
Consider the following (contrived) code:
```
struct A
    x::Float64
end

struct B
    xs::Vector{A}
end

const y = 1:2500

fn(a::A, t) = sum([t / a.x])
fn(b::B, t) = sum(t / a.x for a in b.xs)

loss(x) = sum(fn(x,t) for t in y)
```

Running `gradient(loss, A(2.0))` takes 928.731 μs. But running `gradient(loss, B([A(2.)]))` takes 107.152 ms. It's over a hundred times slower. Why? What's going on here?

**Comment by ToucheSir** [comment]
The extraordinarily high runtime of `gradient(loss, A(2.0))` gives us a hint as to what's happening. We can confirm it by looking at what Zygote generates:
```julia
julia> Zygote.@code_adjoint loss(A(2.0))
Zygote.Adjoint(1: (%3, %4 :: Zygote.Context, %1, %2)
  %5 = Main.:(var"#5#6")
  %6 = Core.typeof(%2)
  %7 = Core.apply_type(%5, %6)
  %8 = Zygote._pullback(%4, Zygote.__new__, %7, %2)
  %9 = Base.getindex(%8, 1)
  %10 = Base.getindex(%8, 2)
  %11 = Zygote._pullback(%4, Zygote.unwrap, $(QuoteNode(:(Main.y))), Main.y)
  %12 = Base.getindex(%11, 1)
  %13 = Base.getindex(%11, 2)
  %14 = Zygote._pullback(%4, Base.Generator, %9, %12)
  %15 = Base.getindex(%14, 1)
  %16 = Base.getindex(%14, 2)
  %17 = Zygote._pullback(%4, Base.collect, %15)
  %18 = Base.getindex(%17, 1)
  %19 = Base.getindex(%17, 2)
  %20 = Zygote._pullback(%4, Main.sum, %18)
  %21 = Base.getindex(%20, 1)
  %22 = Base.getindex(%20, 2)
  return %21, 1: (%1)
  %2 = (@22)(%1)
  %3 = Zygote.gradindex(%2, 2)
  %4 = (@19)(%3)
  %5 = Zygote.gradindex(%4, 2)
  %6 = (@16)(%5)
  %7 = Zygote.gradindex(%6, 2)
  %8 = Zygote.gradindex(%6, 3)
  %9 = (@13)(%8)
  %10 = (@10)(%7)
  %11 = Zygote.gradindex(%10, 2)
  %12 = Zygote.gradindex(%10, 3)
  %13 = Zygote.tuple(nothing, %12)
  return %13)
```
In short, `sum(<expression> for <var> in <collection>)` desugars to `sum(Generator(<var> -> <expression>, <collection>))`. There is no native AD rule for this path, so Zygote digs into the function and proceeds to generate less-than-optimal code when it inevitably encounters large amounts of control flow (as well as perhaps scalar indexing and other things it can't optimize). Given this, you can imagine what gets generated when the call stack contains nested `sum`s over generators.

One thing you can do here is switch the generator comprehensions over to array comprehensions:

```julia
loss(x) = sum([fn(x,t) for t in y])
fn(b::B, t) = sum([t / a.x for a in b.xs])

# Baseline times are a little slower on my machine, but not by much
julia> @btime gradient(loss, A(2.0));
  135.460 μs (2557 allocations: 705.27 KiB)

julia> @btime gradient(loss, B([A(2.)]));
  5.492 ms (120097 allocations: 4.89 MiB)
```

At first blush this seems counter-intuitive, because if anything `sum(array comprehensions)` a) allocates more, b) has to fill the whole array before summing and thus iterates over it twice. However, because we're able to define an [optimized AD rule](https://github.com/FluxML/Zygote.jl/blob/a4eac890f41e7072ef5b571da101b8f498e49b2c/src/lib/array.jl#L230-L238) for it, in practice it runs much faster under AD.

Depending on your use case, replacing `sum([...])` with `sum(f, ...)` could also work. It's sometimes a little slower, sometimes a little faster on my machine, but it'll save you an allocation when not taking gradients.

**Comment by bogiebro** [comment]
Thanks! Yes, using `sum(f, ...)` worked for my use case.
