### ISSUE TITLE
Mutating array error when array isn't mutated

### ISSUE THREAD

**Issue by jrwrigh** [FluxML/Zygote.jl#1308]
I have a function where I form the output array `R` via for loops, one loop per entry to `R`. Something similar to this:

```julia
function testf(x)
    n = 10
    R = zeros(n)
    for i in 1:n
        R[i] = x[i]^2
    end
    R
end

jacobian(testf, float(collect(1:n)))
```
The above falls under the documentations definition of a "pure function" (`x` is not changed, `R` is only dependent on `x`).

However, I get A mutating error message back:
```
Mutating arrays is not supported -- called setindex!(Vector{Float64}, ...)
This error occurs when you ask Zygote to differentiate operations that change
the elements of arrays in place (e.g. setting values with x .= ...)

Possible fixes:
- avoid mutating operations (preferred)
- or read the documentation and solutions for this error
  https://fluxml.ai/Zygote.jl/latest/limitations


Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _throw_mutation_error(f::Function, args::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/lib/array.jl:68
  [3] (::Zygote.var"#385#386"{Vector{Float64}})(#unused#::Nothing)
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/lib/array.jl:80
  [4] (::Zygote.var"#2312#back#387"{Zygote.var"#385#386"{Vector{Float64}}})(Δ::Nothing)
    @ Zygote ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67
  [5] Pullback
    @ ./In[154]:5 [inlined]
  [6] (::typeof(∂(testf)))(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/compiler/interface2.jl:0
  [7] #208
    @ ~/.julia/packages/Zygote/PD12J/src/lib/lib.jl:206 [inlined]
  [8] (::Zygote.var"#1914#back#210"{Zygote.var"#208#209"{Tuple{Tuple{Nothing}}, typeof(∂(testf))}})(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67
  [9] Pullback
    @ ./operators.jl:1035 [inlined]
 [10] (::typeof(∂(#_#95)))(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/compiler/interface2.jl:0
 [11] (::Zygote.var"#208#209"{Tuple{Tuple{Nothing, Nothing}, Tuple{Nothing}}, typeof(∂(#_#95))})(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/lib/lib.jl:206
 [12] #1914#back
    @ ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67 [inlined]
 [13] Pullback
    @ ./operators.jl:1033 [inlined]
 [14] (::typeof(∂(ComposedFunction{typeof(Zygote._jvec), typeof(testf)}(Zygote._jvec, testf))))(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/compiler/interface2.jl:0
 [15] (::Zygote.var"#60#61"{typeof(∂(ComposedFunction{typeof(Zygote._jvec), typeof(testf)}(Zygote._jvec, testf)))})(Δ::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/compiler/interface.jl:45
 [16] withjacobian(f::Function, args::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/lib/grad.jl:150
 [17] jacobian(f::Function, args::Vector{Float64})
    @ Zygote ~/.julia/packages/Zygote/PD12J/src/lib/grad.jl:128
 [18] top-level scope
    @ In[154]:10
 [19] eval
    @ ./boot.jl:368 [inlined]
 [20] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1428
```

Is this a bug? If not, is there a work around/correct way to do this?

**Comment by ToucheSir** [comment]
I'm not sure I follow. `R[i] = x[i]^2` is perhaps the most common example of mutation. We don't include it as an example in the error message or docs because we assume a common understanding (in Julia land) that `array[index] = value` translates to `setindex!(array, ...)` and setting array elements absolutely counts as mutation.

As for workarounds, you have a couple options. Vectorizing your loop into a broadcast like `R = x.^2` will avoid the mutation error and be much faster to boot. If for whatever reason you must have the loop, then [`Buffer`](https://fluxml.ai/Zygote.jl/latest/utils/#Zygote.Buffer) exists with the tradeoff of having very poor performance (and thus we recommend to never use it unless you have no other choice).

**Comment by ToucheSir** [comment]
Ah, I think I see your point of confusion now. Whereas `testf` is a "pure" function (really [referentially transparent](https://en.wikipedia.org/wiki/Referential_transparency)) by the definition in the docs, it contains within the "impure" mutating `R[i] = ...`. To use the language of the docs, `testf` is neither of the "primitive" functions `f`, `g`, or `h`, but a composite function `testf(x) = h(g(f(x)))`. So if any of those functions are mutating, you'll still get an error because Zygote recurses until it finds AD primitives it has rules defined for.

If you had written a custom rule for `testf`, then it _would_ be treated like `f/g/h` because Zygote wouldn't try to recurse into it. This is many stdlib functions which mutate under the hood (but not their inputs, there's that referential transparency again) are defined.

**Comment by jrwrigh** [comment]
> We don't include it as an example in the error message or docs because we assume a common understanding (in Julia land) that array[index] = value translates to setindex!(array, ...) and setting array elements absolutely counts as mutation.

Ah, I am very new to Julia land. I'm familiar with "pure" in the Fortran sense (which is what is defined in the documentation, though with the addition that in/out variables are allowed if they're declared). I can see now how mutation == mutable, which is exactly what I'm doing with the array. Perhaps a definition of mutation might be helpful in the documentation (which I'm guessing is effectively overwriting any variable in the function; variables may only be their initialized value). 

As for the solution, my actual problem can't be done as a broadcast because different parts of `R` need to have different values set. For example:
```julia
function testf(x)
    n = 10
    R = zeros(2*n)

    R[1] = x[1]
    for i in 2:n
        R[i] = x[i]^2
    end
    for i in n+1:2*n
        R[i] = x[i-n]^4
    end
    R
end
```

The solution that (appears for right now at least) to work for me is:
```julia
function testf(x)
    vcat(x[1], x.^2, x.^4)
end
```
Thanks for your help!
