### ISSUE TITLE
Derivative of Custom Types that Subtypes Number

### ISSUE THREAD

**Issue by tansongchen** [FluxML/Zygote.jl#1319]
I had trouble taking derivatives of some code involving custom types that subtypes `Number`. Specifically, the following code works:

```julia
using Zygote

struct M{T<:Number}
    value::T
end

Base.:*(a::M, b::M) = M(a.value * b.value)

function f(x)
    m = M(x)
    result = m * m
    return result.value
end

gradient(f, 1.)
```

but if I let `M` subtypes `Number` and give corresponding promoting rules, the following code does not work:

```julia
using Zygote

struct M{T<:Number} <: Number
    value::T
end

Base.:*(a::M, b::M) = M(a.value * b.value)
Base.adjoint(a::M) = a
Base.promote_rule(::Type{M{T}}, ::Type{T}) where {T<:Number} = M{T}
Base.convert(::Type{M{T}}, x::T) where {T<:Number} = M(x)

function f(x)
    m = M(x)
    result = m * m
    return result.value
end

gradient(f, 1.)
```

and gives error like this:

```
ERROR: LoadError: MethodError: no method matching (::ChainRulesCore.ProjectTo{Number, NamedTuple{(), Tuple{}}})(::ChainRulesCore.Tangent{Any, NamedTuple{(:value,), Tuple{M{Float64}}}})
Closest candidates are:
  (::ChainRulesCore.ProjectTo{T})(::ChainRulesCore.Tangent{<:T}) where T at ~/.julia/packages/ChainRulesCore/C73ay/src/projection.jl:143
  (::ChainRulesCore.ProjectTo)(::ChainRulesCore.Thunk) at ~/.julia/packages/ChainRulesCore/C73ay/src/projection.jl:124
  (::ChainRulesCore.ProjectTo{<:Number})(::Number) at ~/.julia/packages/ChainRulesCore/C73ay/src/projection.jl:185
  ...
Stacktrace:
 [1] (::ChainRules.var"#times_pullback2#1333"{M{Float64}, M{Float64}})(Ω̇::ChainRulesCore.Tangent{Any, NamedTuple{(:value,), Tuple{Float64}}})
   @ ChainRules ~/.julia/packages/ChainRules/KVV0e/src/rulesets/Base/fastmath_able.jl:257
 [2] ZBack
   @ ~/.julia/packages/Zygote/dABKa/src/compiler/chainrules.jl:206 [inlined]
 [3] Pullback
   @ ~/Applications/TaylorDiff.jl/test/mwe.jl:14 [inlined]
 [4] (::typeof(∂(f)))(Δ::Float64)
   @ Zygote ~/.julia/packages/Zygote/dABKa/src/compiler/interface2.jl:0
 [5] (::Zygote.var"#60#61"{typeof(∂(f))})(Δ::Float64)
   @ Zygote ~/.julia/packages/Zygote/dABKa/src/compiler/interface.jl:45
 [6] gradient(f::Function, args::Float64)
   @ Zygote ~/.julia/packages/Zygote/dABKa/src/compiler/interface.jl:97
 [7] top-level scope
   @ ~/Applications/TaylorDiff.jl/test/mwe.jl:18
in expression starting at /Users/tansongchen/Applications/TaylorDiff.jl/test/mwe.jl:18
```

Any suggestions on this?

**Comment by ToucheSir** [comment]
The reason is because `*` calls into ChainRules, which uses `ProjectTo`: https://github.com/JuliaDiff/ChainRules.jl/blob/v1.44.7/src/rulesets/Base/fastmath_able.jl#L257. Ordinarily, this would hit an overload like https://github.com/JuliaDiff/ChainRulesCore.jl/blob/07dfe6078ab2ba8861c0f78d80403097b5076a7f/src/projection.jl#L193. However, the Zygote <-> ChainRules bridge is lossy and thus we get a `Tangent{Any}` instead of a `Tangent{<:Number}`.

Assuming you want to avoid a Zygote dependency, there are a couple things you can try. The most direct approach is to convert that `@adjoint` into a `rrule`. That solves the proximal issue but probably doesn't scale. A more indirect but general route is to define the external constructor `ProjectTo(::M) = ProjectTo{M}()` à la https://github.com/JuliaDiff/ChainRulesCore.jl/blob/07dfe6078ab2ba8861c0f78d80403097b5076a7f/src/projection.jl#L158-L160, then (this is slightly hacky) define `(::ProjectTo{<:M})(::Tangent{Any, NamedTuple{(:value,), Tuple{M{<:Number}}})`.
