### ISSUE TITLE
Use differential for more intuitive derivative definition

### ISSUE THREAD

**Issue by sdewaele** [FluxML/Zygote.jl#135]
As Zygote is AD for the 21st century, perhaps we can use the opportunity to make the definition of derivatives for  linear algebra operations more intuitive, namely using the [differential](https://en.wikipedia.org/wiki/Differential_of_a_function#General_formulation), instead of the adjoint. The motivation is that it is more intuitive to use:

* Derivatives of linear algebra operations are more easily described using differentials. See, for example, the [matrix cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf), chapter 2.

* Many users will be familiar with the Jacobian matrix `J`, which is the matrix representation of the differential. Therefore, the differential `D` of a function can simply be written as:
```
D(Δ) = J*Δ
```
Whereas the adjoint `G` requires a double transpose:
```
G(Δ) = Δ'*J'
```
which is less intuitive.

It is a general observation that the differential requires fewer `transpose` operations. For example, the [adjoint for the matrix inverse](https://github.com/FluxML/Zygote.jl/blob/99b26717b1b3ad1e72613e34eb518204317ee656/src/lib/array.jl#L194)   is given by:
```
function G(Δ)
        Ainv = inv(A)
        ∇A = - Ainv' * Δ * Ainv'
        return (∇A, )
end
```
while with the differential, coded straight from the cheat sheet, eliminates the transpose:
```
function D(Δ)
        Ainv = inv(A)
        dA = - Ainv * Δ * Ainv
        return (dA, )
end
```

I would propose to introduce an new macro, e.g. `@differential`, that will take over the role of `@adjoint` in these cases.

I am happy to hear comments from the experts. While I am currently not familiar with the full code base, I can certainly go through [src/lib/array.jl](https://github.com/FluxML/Zygote.jl/blob/master/src/lib/array.jl) and apply the simplification there.

**Comment by MikeInnes** [comment]
IIUC correctly, you're effectively advocating for using forward-mode rules (AKA differentials, tangents, Jacobian-vector products etc) instead of reverse-mode ones (adjoints, sensitivities, vector-Jacobian products – yes this field has a terminology problem).

Adjoints are really more fundamental in Zygote, which is an adjoint-generator rather than a differential-generator. When we derive `c = a*b` we don't actually have `da` and `db`, we have `dc` and need to work backwards. In some special cases (like `inv`) it's easy to go between differential and adjoint, but in other cases it can't be done automatically.

Jax actually does something like this; they just write down all the rules in forward mode, record the tape and then transpose the whole tape to get reverse mode. It's a nice design but the caveats are that (a) it's not obvious how to implement it in Julia and (b) a lot of our rules are things like `getindex` which we'd have to specify adjoints for anyway.

**Comment by jekbradbury** [comment]
> Jax actually does something like this; they just write down all the rules in forward mode, record the tape and then transpose the whole tape to get reverse mode. It's a nice design but the caveats are that (a) it's not obvious how to implement it in Julia and (b) a lot of our rules are things like `getindex` which we'd have to specify adjoints for anyway.

More details on JAX's system for anyone who's curious:

Every primitive function is either linear or nonlinear in each of its arguments. For primitives that are nonlinear in some or all of their arguments, JAX implements a forward-mode AD (their term is "linearization") rule, while no linearization rule is needed for primitives/arguments that are already linear. JAX also includes adjoint (they say "transpose") rules for all linear primitives that perform the linear operator adjoint (these are exactly the same as reverse-mode AD rules). The result is that they only need to define a single rule for each primitive (or primitive-argument pair in the case of partially linear primitives).

JAX can get away with this because of their procedure for computing adjoints of composite functions. First they linearize the function (replacing every nonlinear primitive with a linear function composed of the primitive's input value and a tangent computed at that "linearization point"). This doesn't need an IR; it's a "final embedding" transformation that Julia could do with plain overloading or Cassette. They then trace the linearized function to create an operation tape (in their case jaxprs) needed for the next step, so Zygote needs to have Julia IR in its hands here. Lastly they "transpose" (take the adjoint of) this traced linear function by reversing the order of the equations in the jaxpr and recursively applying the transpose transformation and its primitive rules. Everything encountered in this pass is linear, so there's no need to implement adjoints for nonlinear primitives.

**Comment by MikeInnes** [comment]
It's also worth noting that you can go the other way easily, and this works in Flux and other reverse-mode ADs too; if you take the gradient of a pullback `J'*v` you get `J*v`, or in other words forward-mode AD. You lose some of the nice properties of forward mode, but it's neat that it works without *anything* extra, and interesting to consider what it would take to get an optimised forward mode out of this.

FWIW I put up some quick notes on the mathematical side of this in the [docs](http://fluxml.ai/Zygote.jl/dev/adjoints/). Hopefully that clears up the confusion about `@adjoint` not being the Jacobian.
