### ISSUE TITLE
Fails to precompile on PkgEval run

### ISSUE THREAD

**Issue by schillic** [FluxML/Zygote.jl#1539]
[Link to latest PkgEval run](https://juliaci.github.io/NanosoldierReports/pkgeval_badges/Z/Zygote.html)
Quite some packages fail as a consequence in that PkgEval run too.

The package builds locally in Julia v1.12 for me. The [PkgEval README](https://github.com/JuliaCI/PkgEval.jl?tab=readme-ov-file#why-does-my-package-fail) describes a way to locally reproduce (which I have not tried).

**Comment by ToucheSir** [comment]
Per GitHub, nightly CI has been broken for a while. Since nobody seems to have the bandwidth to fix it, it'll probably stay this way.

This specific failure seems to be from upstream and not Zygote itself. If I had to guess, https://github.com/FluxML/IRTools.jl/pull/131 is related. As such, I'm closing this issue to redirect people there.
