### ISSUE TITLE
exp broken for defective matrices

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#340]
The current implementation for the adjoint of `exp` relies on the eigenvalues of its argument being distinct. This isn't always the case, and I've found examples in my work where I need the exponential of a matrix which is defective by construction, so this assumption doesn't hold.

I've hacked together a solution that works for my research (a slow but accurate differentiable Pade approximation -- this operation is not a computational bottleneck in my work) so it's not blocking for me. Would be nice to resolve though.

**Comment by sdaxen** [comment]
I ran into this today as well. FWIW, for my work, this likely will be my major computational bottleneck, though because my matrices are Hermitian, the eigenvalue approach will likely be the most efficient for me. Is the best option here an autodiffable scaling/squaring approach, or is there a way to get an accurate adjoint when eigenvalues are non-distinct?

**Comment by antoine-levitt** [comment]
Yeah the current implementation is bad. I don't know about non-hermitian, but for hermitian matrices the problem is that the adjoint computes `(exp(l1)-exp(l2))/(l1-l2)`, which is bad when l1 and l2 are close. In the case of exp fortunately there is a simple fix: (untested)

```
expdiff(x,y) = x == y ? exp(x) : exp(x)*(expm1(y-x)/(y-x))
```
This relies on arithmetic not being associative, so will probably break if fastmath is enabled globally.

For general matrix functions, this is more tricky. The simplest solution is to check whether the difference is smaller than sqrt(eps(T)), and switch to `(f(y)-f(x))/(y-x) \approx f'(x)` if it is. Less elegant than the above, but should work fine (with a degradation of accuracy of sqrt(eps(T)) in the worst case).

Yet another more complicated problem is the adjoint of the diagonalization. This should be OK in theory: if the output does not do something stupid (like differentiate between eigenvectors that are close), the perturbation should have zeros in the appropriate components; numerically though, that might be tricky.

**Comment by sdaxen** [comment]
Thanks @antoine-levitt , do you have more I can read about this?

> Yet another more complicated problem is the adjoint of the diagonalization. This should be OK in theory: if the output does not do something stupid (like differentiate between eigenvectors that are close), the perturbation should have zeros in the appropriate components; numerically though, that might be tricky.

This is for Hermitian matrices, right? My understanding is that the scaling/squaring approach is considered the safest general approach for exponentiating, and it's adjoint is computed easily (though maybe not efficiently?) from elementary operations (e.g. in Giles). For Hermitian matrices, the eigendecomposition approach is more efficient and generally safe unless the eigenvalues are degenerate. This is what LinearAlgebra does, but it mutates. The current adjoint is wasteful for `exp(::Union{Symmetric,Hermitian})`, since it recomputes the eigendecomposition instead of reusing it. I confess I don't really understand perturbation.

**Comment by antoine-levitt** [comment]
What do you want to read about exactly? The derivative of matrix functions should be somewhere in the book "functions of matrices" by Higham. My favorite derivation uses contour integrals, which reduces to the problem of computing perturbations of inverses.

Yes, that was for Hermitian. I have much less experience with non-Hermitian, but there eigendecomposition is bad, so something else should be used.
