### ISSUE TITLE
Intermediate complex number causes complex gradient

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Zygote.jl#472]
The following code unexpectedly returns a complex gradient:
```julia
using Zygote
Zygote.refresh()
function f(x)
    return real(x[1] + im * x[1])
end
Zygote.gradient(f, [1.0])
# (Complex{Float64}[1.0 - 1.0im],)
```
Note that the input is real and the output is real.

**Comment by Paethon** [comment]
I can replicate this.
I assume this happens because at one step the gradient is complex and since the gradients are just updated by multiplication, all gradients after that are complex as well?

**Comment by mcabbott** [comment]
Yes, right now Zygote naturally works over the complex numbers, and just happens to give real gradients in many cases, as it gives integer gradients in some. See #342 for some discussion. (My vote would be to change this, and clamp the gradients of real-valued parameters to be real numbers.)

**Comment by MikeInnes** [comment]
FWIW, this may change as part of a larger overhaul in which we fix the gradient type for all types. Firstly, because it's hard to change this just for complex/real without changing it everywhere, but also because we may need that kind of restriction to integrate more deeply with the Julia compiler and to make some optimisations. The same would apply to the sparse issue.

For now, closing as a dup of #342; I hope the discussion helped clear up some of the surprise about this.
