### ISSUE TITLE
Reverse-mode AD through broadcast

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Zygote.jl#71]
After discussions with @willtebbutt I'm convinced that we should throw out the mixed-mode broadcast implementation in favour of a reverse-mode version. It's now possible to do this without giving up fusion, given that Zygote's output is generally GPU-compatible.

Mixed-mode broadcast turns out to be pretty heavy on the compiler and memory bandwidth (exponentially so in the case of nested AD). It also makes it pretty difficult to support things like complex-number AD, which should just work if we have a Zygote-based version.

The downside is that Zygote's stacks will not be GPU-compatible, so code with loops is going to break there; CPU will work though the extra memory accesses may mean a perf hit. That's ok though, for the rare case this is useful we can keep it as an option.

The major blocker right now is having a multi-output broadcast / map. I don't think this is too hard to put together but it might take some time to make sure it's mature enough, SIMD-able, deals with inferred return types properly, etc.

**Comment by willtebbutt** [comment]
Glad to hear you think this is a sane idea. Who would be an good person to work on the multi-output version of `broadcast` and `map`?

**Comment by MikeInnes** [comment]
I think anyone could start the work off and get most of the way there; we don't need the really polished version to get going. Happy to help anyone who wants to hack on it, or I'll put something together myself if no-one gets there before me.

**Comment by jrevels** [comment]
> memory bandwidth (exponentially so in the case of nested AD)

Which specific issue is being referred to here? The memory bandwidth for the broadcast kernel itself (e.g. the amount of stack memory required to propagate partials in the elementwise kernel invocation), or memory bandwidth at the trace-level (the amount of memory required to cache the resulting partial tensors before doing the multiply)?

The former is more complicated (chunk size tuning, yayyyyy), but the latter is more easily tunable, e.g. there's no need to cache the partial arrays in the forward pass rather than compute on the fly in the backwards pass. Not sure if that's already what's being done now. The most efficient choice (applying forward-mode in the forwards pass vs. applying it in the backwards pass) depends on trace-level memory bandwidth. 

> The downside is that Zygote's stacks will not be GPU-compatible, so code with loops is going to break there; CPU will work though the extra memory accesses may mean a perf hit. That's ok though, for the rare case this is useful we can keep it as an option.

Seems better to do forward-mode by default and only switch to reverse-mode for the cases in which it is easy to statically detect that there isn't any problematic dynamism (e.g. requires stack insertion)? It's the case where the primal code exhibits a certain degree of dynamism that forward-mode ADing the kernel is actually the right thing to do, rather than just the easy thing.

**Comment by jrevels** [comment]
> makes it pretty difficult to support things like complex-number AD

there shouldn't be any forward-mode-specific problems with complex AD?

**Comment by roberthoenig** [comment]
I'd be happy to give `map` a shot. Is the following in any sense close to what we want?
```julia
@adjoint function map(f, args...)
  map(f, args...), function (Δ)
    Δargs_tuples = Zygote.gradient.(f, args...)
    Δargs = map(i-> Δ.*getindex.(Δargs_tuples, i), 1:length(args))
    (nothing, Δargs...)
  end
end

Zygote.gradient((x,y)->sum(map((a,b) -> a^b, x, y)), [1,2,3], [4,5,6])

([4, 80, 1458], [0.0, 22.1807, 800.888])
```
Also, what is meant by "multi-output" map? Multiple outputs in the sense that calling `map` with multiple collection arguments will lead to a gradient with multiple collection partials?

**Comment by MikeInnes** [comment]
> there shouldn't be any forward-mode-specific problems with complex AD?

You have to at least make the number of seeds depend on the types of the inputs, make that infer properly etc, then specify how to dual-ify `Complex`. I don't think any of the problems here are fundamentally unresolvable, but it's a lot of effort compared to just making reverse mode work, which we need for the general case anyway (e.g. custom struct types, which are more common IMO than kernels with loops). Of course if chunk size tuning is someone's idea of fun and they want to write it, we can just dispatch to that where it makes sense.

**Comment by MikeInnes** [comment]
@roberthoenig that's definitely getting there. You'd probably want to use `forward` and store an array of pullbacks, and you can then broadcast the pullbacks over the incoming sensitivity.

I shouldn't have describe multi-output broadcast as a blocker, since you can get the same effect by doing multiple maps (e.g. compute a tuple and then index it). It'd just be a perf boost, but we can certainly write down a prototype that doesn't use that.

**Comment by jekbradbury** [comment]
Forward-mode AD on custom struct types is pretty much the core competency of Cassette's typed metadata system, though, right?

**Comment by MikeInnes** [comment]
Indeed, though I think you'd still need much of the same utilities for seeding and extracting gradients, heuristics for chunk size etc.

**Comment by MikeInnes** [comment]
A timely example: https://github.com/FluxML/Flux.jl/issues/659.
