### ISSUE TITLE
Optimising some linear algebra related adjoints 

### ISSUE THREAD

**Issue by DhairyaLGandhi** [FluxML/Zygote.jl#773]
There are some adjoints which repeat calculations in the backwards pass which can be avoided.

https://github.com/FluxML/Zygote.jl/blob/master/src/lib/array.jl#L429-L443
This refactorizes  `A'` and can be replaced with `factorize` and use that in the backwards pass

https://github.com/FluxML/Zygote.jl/blob/master/src/lib/array.jl#L457-L459
We need to fix `ldiv!` to get performance jumps here.

**Comment by devmotion** [comment]
Couldn't/Shouldn't these adjoints be removed since they are already defined in ChainRules, e.g., https://github.com/JuliaDiff/ChainRules.jl/blob/bb08bd80b5cee92947002547de1f54556a5e3ee7/src/rulesets/LinearAlgebra/dense.jl#L284-L310? If there are performance improvements possible, they could be contributed to ChainRules such that all ChainRules-compatible AD backends can make use of them.

**Comment by DhairyaLGandhi** [comment]
Correct, the PR must be made against ChainRules.jl, and we can get rid of the code in here.

**Comment by DhairyaLGandhi** [comment]
Props to @ChrisRackauckas who originally identified the right areas to improve

**Comment by DhairyaLGandhi** [comment]
Opened the new issue in ChainRules. Closing this one in favour of it.
