### ISSUE TITLE
Gradient checkpointing?

### ISSUE THREAD

**Issue by jw3126** [FluxML/Zygote.jl#884]
How to do gradient checkpointing? Is it implemented in Zygote or some other package in the ecosystem?
I tried
```julia
using Zygote, ChainRulesCore

function checkpointed(f, args...)
    f(args...)
end

function ChainRulesCore.rrule(::typeof(checkpointed), f, xs...)
    y = f(xs...)
    function pullback_checkpointed(Δy)
        y, pb =Zygote.pullback(f, xs...) 
        return pb(Δy)
    end
    y, pullback_checkpointed
end
```
but it does not work:
```julia
y, pb = Zygote.pullback(checkpointed, sin, pi/2)
pb(1.0)]
()
```

**Comment by willtebbutt** [comment]
Thanks for raising the question. Your example nearly works, it's just missing a couple of details:

Firstly, `ChainRulesCore.rrules` return the cotangent w.r.t. the arguments _and_ the function, while `Zygote.pullback` just returns the cotangents w.r.t. the arguments. Consequently, the following should work as intended:
```julia
function ChainRulesCore.rrule(::typeof(checkpointed), f, xs...)
    y = f(xs...)
    function pullback_checkpointed(Δy)
        y, pb =Zygote.pullback(f, xs...) 
        return ChainRulesCore.NO_FIELDS, pb(Δy)
    end
    y, pullback_checkpointed
end
```

Secondly, this is a situation in which you're calling back into `Zygote`, so it' better to use `Zygote`'s rule-definition system here so that you can preserve `Zygote`s context. I believe this would be the ideal solution:

```julia
function Zygote._pullback(ctx::Zygote.AContext, ::typeof(checkpointed), f, xs...)
    y = f(xs...)
    function pullback_checkpointed(Δy)
        y, pb = Zygote._pullback(ctx, f, xs...)
        return pb(Δy)
    end
    return y, pullback_checkpointed
end
```
I'm interacting directly with `Zygote`s internal `_pullback` function, which exposes the`Context` variable, and also has the same returns as `rrule` (it return cotangents w.r.t. the function itself and the arguments)`.

Let me know if this resolves your problems.

**Comment by jw3126** [comment]
Thanks a lot. Since this is non-trivial and uses Zygote internals, how about adding it to Zygote? I can do a PR if you like.

**Comment by willtebbutt** [comment]
That would be great -- I'm happy to review.
