### ISSUE TITLE
Gradient of sum

### ISSUE THREAD

**Issue by cossio** [FluxML/Zygote.jl#900]
```julia
T = randn(10,10)
ps = Flux.params(T)
opt=ADAM()
for iter = 1:100
    gs = gradient(ps) do
        sum(T)
    end
    Flux.update!(opt, ps, gs)
end
```

Throws the following error:

> 
> ArgumentError: Cannot setindex! to 0.0009999999900000003 for an AbstractFill with value 1.0.
> 
> Stacktrace:
>  [1] setindex! at /home/cossio/.julia/packages/FillArrays/tE9Xq/src/FillArrays.jl:41 [inlined]
>  [2] _setindex! at ./abstractarray.jl:1176 [inlined]
>  [3] setindex! at ./abstractarray.jl:1153 [inlined]
>  [4] macro expansion at ./broadcast.jl:932 [inlined]
>  [5] macro expansion at ./simdloop.jl:77 [inlined]
>  [6] copyto! at ./broadcast.jl:931 [inlined]
>  [7] copyto! at ./broadcast.jl:886 [inlined]
>  [8] materialize! at ./broadcast.jl:848 [inlined]
>  [9] materialize!(::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(*),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(/),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(/),Tuple{Array{Float64,2},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(-),Tuple{Int64,Float64}}}},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(+),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(sqrt),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(/),Tuple{Array{Float64,2},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(-),Tuple{Int64,Float64}}}}}},Float64}}}},Float64}}) at ./broadcast.jl:845
>  [10] apply!(::ADAM, ::Array{Float64,2}, ::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}) at /home/cossio/.julia/packages/Flux/05b38/src/optimise/optimisers.jl:177
>  [11] update!(::ADAM, ::Array{Float64,2}, ::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}) at /home/cossio/.julia/packages/Flux/05b38/src/optimise/train.jl:23
>  [12] update!(::ADAM, ::Params, ::Zygote.Grads) at /home/cossio/.julia/packages/Flux/05b38/src/optimise/train.jl:29
>  [13] top-level scope at In[89]:8
>  [14] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
>

**Comment by cossio** [comment]
This is really an issue with Flux, since the gradient is fine.
https://github.com/FluxML/Flux.jl/issues/1510

**Comment by GiggleLiu** [comment]
I think it is an issue of Zygote, it returns FillArray as the gradient of sum. That is very unfortunate, a lot people around me bump to this bug.

**Comment by cossio** [comment]
But I think it's fine to say that the gradient of `sum` is a `FillArray`. It's a correct answer that is more efficient in most cases.

**Comment by willtebbutt** [comment]
> I think it is an issue of Zygote, it returns FillArray as the gradient of sum. That is very unfortunate, a lot people around me bump to this bug. https://github.com/FluxML/Zygote.jl/pull/191/files

To my mind, this is perfectly acceptable behaviour -- it's similar in flavour to returning `nothing` if the gradient w.r.t. an `Array` input to some function is always `0`. Could you explain why you feel that this is a bug?

**Comment by GiggleLiu** [comment]
> Could you explain why you feel that this is a bug?

When user writes backward rules, he always assume the adjoint of the output has the same type as the output. Simply because it is impossible to handle various adjoint types.

Here if you have a function `loss = sum(f(x))`, where the function `f(x)` returns an Array `y`. If we assume `adjoint_y` type is Array or Nothing. Then he might use `setindex!` in his program and get an error. This kind of bug can not be detected with unit tests.

**Comment by willtebbutt** [comment]
> When a user writes backward rules, he always assume the adjoint of the output has the same type as the output. Simply because it is impossible to handle various adjoint types.

Right -- I think this is the crux of the problem. Users should not be making this assumption because Zygote has never promised to provide a gradient of the same type as the argument, nor could it feasibly do so. Probably the documentation should be changed to reflect this.

For example, general `struct`s have `NamedTuple` gradients (hopefully `ChainRules`'s `Composite`s at some point in the future instead) just because you can't represent the gradient of a function w.r.t. some arbitrary `struct` with another `struct` of the same type. It's not even always the case that `AbstractArray`s can have "sensible" gradient representations that are of the same type as the argument -- `Fill`s are actually a good example here, as representing the gradient of a function w.r.t. a `Fill` turns out to have slightly strange consequences.

Perhaps we should consider some additional functionality to "canonicalise" representations. We've actually been discussing implementing that kind of functionality for `ChainRules` to make rule-implementers lives more straightforward -- see [here](https://github.com/JuliaDiff/ChainRulesCore.jl/issues/286). We might be able to optionally incorporate something like this in `Zygote`.

**Comment by GiggleLiu** [comment]
It is good to know someone is taking it seriously. I can see it is hard to unify the adjoint, like the `Tranpose{T,Vector{T}}` output might have a regular vector as adjoint, also those with the NamedTuple as returns.

I am thinking how much performance loss if we force the adjoint to have the same type as the output. Julia language used to return normal array type if you call zero on another type ([see issue](https://github.com/JuliaLang/julia/issues/29839)), but now it also changes the behavior
```julia
julia> zero([1,2,3]')
1×3 adjoint(::Vector{Int64}) with eltype Int64:
 0  0  0
```

For composite types, I can imagine it requires users' effort to wrap it with the right type. Wondering if there is a fundamental reason for not doing so?

Also, I am interested to know if there is a benchmark to show returning the same type sacrifises the performance a lot. I am just curious the cons and pros for doing so, without strong bias toward one over another.

**Comment by willtebbutt** [comment]
> I am also thinking how much performance loss if we force the adjoint to have the same type as the output.

Are you specifically referring to `AbstractArray`s here, or more general types?

> Also, I am interested to know if there is a benchmark to show returning the same type sacrifises the performance a lot. I am just curious the cons and pros for doing so, without strong bias toward one over another.

I'm not aware of any particular benchmarks -- would be interesting to see some.

**Comment by GiggleLiu** [comment]
> Are you specifically referring to AbstractArrays here, or more general types?

I mean more general types.

**Comment by willtebbutt** [comment]
> I mean more general types.

Okay. For more general types this isn't a matter of performance, it's about achieving the correct / desirable behaviour. There are a couple of reasons for this. Consider an arbitrary `struct` `Foo`.

Firstly, as an AD package author, you're not allowed to define `+(::Foo, ::Foo)` or `*(::Real, ::Foo)`, because that would be type-piracy. Also because it's possible that `Foo` could have an inner-constructor that would prevent us from constructing an appropriate (co)tangent. However, we need (co)tangents to form a vector space, so we need to be able to define those operations.

Secondly, it's not always the case that the set of points that a given type can represent is the same as its tangent space. For example, suppose that
```
struct Foo
    x::Float64
    lb::Float64
    ub::Float64
    function Foo(x, lb, ub)
        if x < lb || x > ub
            throw(error("x must be between lb and ub"))
        end
        return new(x, lb, ub)
    end
end
```
I've used an inner construct to constrain the value of `x` to be somewhere between `lb` and `ub`, so you're now allowed to construct a `Foo` that violates this assumption. So `x ∈ [lb, ub]`, but the derivative of some function w.r.t. `x` needn't satisfy this constraint, since the tangent space of `x` is the entire real line.

Does this make sense?

**Comment by GiggleLiu** [comment]
Thanks for you reply.
About the first point, can you explain " we need (co)tangents to form a vector space" a bit more? I do not get it.

In the second point, this example is excellent. I also have such issue even in NiLang. This is because the constructor did some checks beyond type information. I think the ideal solution is to add something like `new(type, fields....)` to access the default constructor in Julia language.

**Comment by willtebbutt** [comment]
>  About the first point, can you explain " we need (co)tangents to form a vector space" a bit more? I do not get it.

Well, strictly speaking, you just need to be able to add tangents to make AD work i.e. accumulation on the reverse-pass in reverse-mode. Scaling is an added bonus really.

> In the second point, this example is excellent. I also have such issue in NiLang. This is because the constructor did some checks beyond type information. I think the ideal solution is to add something like new(type, fields....) to access the default constructor in Julia language.

I think you actually can do this with some existing hack that people disapprove of. @oxinabox you mentioned this to me a while ago I think.

I really don't favour that solution though, since it doesn't make sense to me semantically. Like, I really don't want to have objects floating around that claim to be constrained, but aren't actually constrained. This is why I prefer the `Composite` approach -- it's explicit in what it represents, e.g. a `Composite{Foo}` represent the (co)tangent of a `Foo`, and doesn't require violating constraints that type authors have placed on their types.

**Comment by oxinabox** [comment]
>   I think you actually can do this with some existing hack that people disapprove of. @oxinabox you mentioned this to me a while ago I think.

Yeah, youcan do it, it is something like
` @eval force_create(T, fields...) = Expr(:new, T, fields...)`

>  I really don't favour that solution though, since it doesn't make sense to me semantically

Yeah, sometimes inner constructors are enforcing invarients.
Consider 
```
struct UnitCirclePoint
    x
    y
    function CirclePoint(x,y)
        x^2 + y^2 == 1 || error()
        new(x, y)
    end
end

foo(c::UnitCirclePoint) = 2*c.x+3*x.y
```
the `UnitCirclePoint` maintains an invarient. It's fields actually occupy a subspace of `R^2` that is only 1D (a nicer representation would just store the angle, but maybe author of this code has a reason not to)

Attempting to update `c` based on the derivative of `foo` is not well defined.
There are several options. Most clear is to error.
But you could compute the projection back on to the circle (via `tan(dx, dy)`).
I think there are also other options also.

**Comment by GiggleLiu** [comment]
> `Tangent{Foo}`

This name is so much more intuitive! I suddenly understand what you meant previously. Now I tend to agree that the solution of using another type might be better. But I have a new question, why not stick to the rule that type `T` has a gradient of either `T`  for vectors and scalars and `Tangent{T}` for composite types. In this way, the complexity of gradient type is still under control. In this way, we will not see and undexpected `FillArray`.

@oxinabox 
> Yeah, youcan do it, it is something like
@eval force_create(T, fields...) = Expr(:new, T, fields...)

I didn't know this. learnt a new way to hack Julia, cheers!

Thank both of you for careful explaining.

**Comment by willtebbutt** [comment]
> This name is so much more intuitive! I suddenly understand what you meant previously. Now I tend to agree that the solution of using another type might be better.

This is a good point. Have opened an [issue](https://github.com/JuliaDiff/ChainRulesCore.jl/issues/305) :)

> But I have a new question, why not stick to the rule that type T has a gradient of either T for vectors and scalars and Tangent{T} for composite types. In this way, the complexity of gradient type is still under control. In this way, we will not see and undexpected FillArray.

Good point. To my mind, the distinction _here_ is performance.

Firstly, correctness: I think it's clear that it is, on some level, not incorrect to return a `Fill` instead of an `Array` if all of the elements of the tangent are indeed the same. By correctness I mean it in the sense that they both satisfy the `AbstractArray` interface (modulo the `setindex` bit), so you would expect to get the same answer regardless. So there aren't basic correctness problems in the same way that there are in the situations discussed above.

This brings us to performance: my feeling is that there are likely notable performance benefits to allowing the (co)tangent of an `Array` to be represented by a `Fill` in some situations, so it would be a shame to preclude them, since constructing `Fill`s are essentially free and `Array`s require time and memory proportional to their size.

Code Complexity: We already allow things like `Thunk`s and `Zero`s in addition to `Array`s to represent the (co)tangents of `Array`s -- this is where we've taken the view that the code-complexity vs performance tradeoff favours the additional code-complexity. So I think that the question is whether we think that allowing `Fill`s also provides a favourable tradeoff.

Honestly, I'm torn regarding the usefulness of `Fill`s to represent tangents. I don't think it's hard to concoct reasonable-looking programmes where you would expect to see some kind of performance gain by using a `Fill` rather than an `Array` to represent a (co)tangent, but I also don't recall ever encountering situations in the wild in which I found that it was essential to use a `Fill` rather than an `Array` to get performant code 🤷 

All this being said, something like [this](https://github.com/JuliaDiff/ChainRulesCore.jl/issues/286) functionality could allow us to have the best of both worlds. To be honest, I think that we probably need it anyway to ensure that rule-writers can get the type that they need to write their rule without having to think too much about all of the types that a particular tangent could possibly take, and once you've got something like this, it matters less if you've got a few different types that could represent a tangent.

**Comment by GiggleLiu** [comment]
Nice, thanks.

If forcing the grdient types being the same as the input is not a proper solution. There are other ways to helping users finding potential bugs of type mismatch.

I am thinking adding a debug option to help user identifing this type of bugs.
e.g. the previous rrule for `inv`
```julia
function rrule(::typeof(inv), x::AbstractArray)
    Ω = inv(x)
    function inv_pullback(ΔΩ)
        return NO_FIELDS, -Ω' * ΔΩ * Ω'
    end
    return Ω, inv_pullback
end
```

We can insert some code for debugging
```julia
function rrule(::typeof(inv), x::AbstractArray)
    Ω = inv(x)
    function inv_pullback(ΔΩ)
        fs, g = NO_FIELDS, -Ω' * ΔΩ * Ω'
        @debug begin
            if typeof(g) <: Union{Zero, ...}  # special types
                  pass
            elseif ((typeof(x) <: Array || isprimitivetype(typeof(x))) && typeof(x) != typeof(g))
                 "warn: array/scalar type mismatch: function = inv, input type = $(typeof(x)), gradient type = $(typeof(g))"
            elseif (Tangent{typeof(x)} != typeof(g) || field_mismatch(x, g))
                 "warn: tagent type mismatch: function = inv, input type = $(typeof(x)), gradient type = $(typeof(g)), expecting a tangent type"
            end
            return fs, g
        end
    end
    return Ω, inv_pullback
end
```

When a user run the code in debug mode, he will see some useful information to help debugging. Does this make sense?
