### ISSUE TITLE
Dev Docs

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#99]
Here are some general comments on the dev docs (which I think are generally really fantastic btw). Please feel free to close this issue at any point / ignore any of my remarks that you don't agree with.

**What Zygote does**

Consider re-writing
```julia
function J(::typeof(foo), x)
  a, da = J(bar, x)
  b, db = J(baz, a)
  return b, b̄ -> da(db(b̄))
end
```
as
```julia
function J(::typeof(foo), x)
  a, da = J(bar, x)
  b, db = J(baz, a)
  return b, function(b̄)
    ā = db(b̄)
    x̄ = da(ā)
    return x̄
  end
end
```
to highlight the structure of the reverse pass. Same for the sin / cos example.

**Closures**
Nice, useful info.

**Entry Points**

It's not quite clear to me what's going on in the `Zygote.@code_adjoint` example, so it might be worth dissecting this a little bit. In particular:

- It looks to me like we actually have two functions here, but I'm not completely sure. What's going on?
-  Why is `@12` a valid symbol? There's not a `%12` in the forwards pass, which is naively what I would have thought that it would refer to. Actually I can't see any `%` symbols corresponding to `@` symbols, so I don't think I really understand what's going on here. Could definitely do with a more in-depth explanation.

**Closure Conversion**
Following on from the first section, consider re-writing
```julia
(p::Pullback{typeof(foo)})(b̄) = p.data[1](p.data[2](b̄))
```
as
```julia
function (p::Pullback{typeof(foo)})(b̄)
  ā = p.data[2](b̄)
  x̄ = p.data[1](ā)
  return x̄
end
```
for the same reason as before.

It might also be worth noting that these `Pullback` structs tend to generate quite complicated type and so _really_ pollute the stack trace. It took me a while to figure out how to read Zygote's stack traces :)

**Debugging**
Nice. Might be good to have a slightly more in depth example with actual stack traces with highlighted code to help ease people into it though. e.g. how to read `Pullback`s.

**Comment by MikeInnes** [comment]
Great feedback, thanks. I agree with all your suggestions so feel free to make those changes if you get around to it. I'll answer a couple of these questions here quickly before filling out the docs more.

> It looks to me like we actually have two functions here

Yes, that's exactly right, just like there are two functions in the manually-transformed code – one for the forward pass and one for the pullback. The only reason they are not "normal" functions is the need to share data between the two, which is what we accomplish with the `Pullback` type.

> Why is `@12` a valid symbol? There's not a %12 in the forwards pass

`%12` just refers to line 12 in the IR, but the printing is a bit confusing. Julia prints `%x =` only when it can see that the result of that line is used somewhere, but `%12` only gets used implicitly, so it doesn't know to do that. But you can always find `%11` and look at the line after it.

Likely useful context: The IR only allows one "simple" expression per line, so `y, back = _forward(f, x)` gets turned into

```julia
%10 = _forward(f, x)
%11 = getindex(%10, 1) # y
%12 = getindex(%10, 2) # back
```

> It might also be worth noting that these Pullback structs tend to generate quite complicated type and so really pollute the stack trace.

Yeah – I actually only realised this recently since they happen to look ok in Juno :) We can add some notes here but I'd quite like to just make those stack traces nicer.

**Comment by willtebbutt** [comment]
My personal feeling is that this issue has been addressed now. Will close and open new docs-related issues as required.
